// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8O90j5DbmKlY-wTKg9eQiKg3-51pbVr8',
    appId: '1:725777369891:web:5c37c3cc4b42036b319a96',
    messagingSenderId: '725777369891',
    projectId: 'mituapp',
    authDomain: 'mituapp.firebaseapp.com',
    storageBucket: 'mituapp.firebasestorage.app',
    measurementId: 'G-7QS8RXGL9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbk7HFIPT4Us4zvH8KwBSwl8kz5lznPgM',
    appId: '1:725777369891:android:3fb34f1f0faaadcc319a96',
    messagingSenderId: '725777369891',
    projectId: 'mituapp',
    storageBucket: 'mituapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrsT-kyqzWTD3fPB49UVsgkgd2anxyByM',
    appId: '1:725777369891:ios:9510cbe7e59e021b319a96',
    messagingSenderId: '725777369891',
    projectId: 'mituapp',
    storageBucket: 'mituapp.firebasestorage.app',
    iosClientId: '725777369891-bdl49rugp5v9fs1or9t8negqehed8j07.apps.googleusercontent.com',
    iosBundleId: 'com.example.mituApp',
  );

}